name: MERN_ChatApp2

services:
  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
      - 4000:4000
    env_file: "./server/.env.production"
    restart: always
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
      args:
        VITE_REST_API: "http://localhost:4000"
    ports:
      - 4173:4173
    depends_on:
      - api

volumes:
  mongo_data:
